---
title: "Download and prepare Angiosperm data"
author: "Jasmijn Hillaert, Ward Langeraert"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
# Load packages
library(tidyverse) # Data wrangling and visualisation
library(here)      # Relative paths
library(sf)        # Work with spatial data

# Source
source(here("source/create_cube/download_occ_cube.R"))

data_path <- here("data", "raw")
```

# Goal

Load and save structured data

# Structured data
## Occurrence data


The zip file is stored under *./data/raw*.

> GBIF.org (15 April 2025) GBIF Occurrence Download  https://doi.org/10.15468/dl.ddzhrc

```{r}


# nolint start: line_length_linter.
query_ang <-  "SELECT
kingdom,
kingdomkey,
phylum,
phylumkey,
class,
classkey,
\"order\",
orderkey,
family,
familykey,
genus,
genuskey,
species,
specieskey,
\"year\",
GBIF_EEARGCODE(1000, decimallatitude, decimallongitude, COALESCE(coordinateuncertaintyinmeters, 1000)) eeacellcode,
IF(ISNULL(orderkey), NULL, SUM(COUNT(*)) OVER (
  PARTITION BY orderkey, GBIF_EEARGCODE(1000, decimallatitude, decimallongitude, COALESCE(coordinateuncertaintyinmeters, 1000)),\"year\")) ordercount,
IF(ISNULL(familykey), NULL, SUM(COUNT(*)) OVER (
  PARTITION BY familykey, GBIF_EEARGCODE(1000, decimallatitude, decimallongitude, COALESCE(coordinateuncertaintyinmeters, 1000)), \"year\")) familycount,
IF(ISNULL(genuskey), NULL, SUM(COUNT(*)) OVER (
  PARTITION BY genuskey, GBIF_EEARGCODE(1000, decimallatitude, decimallongitude, COALESCE(coordinateuncertaintyinmeters, 1000)), \"year\")) genuscount,
COUNT(*) occurrences,
MIN(GBIF_TEMPORALUNCERTAINTY(eventdate, eventtime)) mintemporaluncertainty,
MIN(COALESCE(coordinateuncertaintyinmeters, 1000)) mincoordinateuncertaintyinmeters
FROM
occurrence
WHERE
(occurrence.level0gid IN ('BEL.2_1', 'BEL.1.1.1_1') OR occurrence.level1gid IN ('BEL.2_1', 'BEL.1.1.1_1') OR occurrence.level2gid IN ('BEL.2_1', 'BEL.1.1.1_1') OR occurrence.level3gid IN ('BEL.2_1', 'BEL.1.1.1_1'))
AND occurrence.occurrencestatus = 'PRESENT'
AND (occurrence.taxonkey IN ('196', '220') OR occurrence.acceptedtaxonkey IN ('196', '220') OR occurrence.kingdomkey IN ('196', '220') OR occurrence.phylumkey IN ('196', '220') OR occurrence.classkey IN ('196', '220') OR occurrence.orderkey IN ('196', '220') OR occurrence.familykey IN ('196', '220') OR occurrence.genuskey IN ('196', '220') OR occurrence.specieskey IN ('196', '220'))
AND (occurrence.\"year\" >= 1975 AND occurrence.\"year\" <= 2025)
AND occurrence.hasgeospatialissues = FALSE
AND NOT GBIF_STRINGARRAYCONTAINS(occurrence.issue, 'TAXON_MATCH_FUZZY', TRUE)
AND NOT occurrence.basisofrecord IN ('FOSSIL_SPECIMEN', 'LIVING_SPECIMEN')
AND (occurrence.specieskey IS NOT NULL AND occurrence.\"year\" IS NOT NULL AND occurrence.\"month\" IS NOT NULL AND occurrence.\"day\" IS NOT NULL AND occurrence.hascoordinate = TRUE)
GROUP BY
occurrence.kingdom,
occurrence.kingdomkey,
occurrence.phylum,
occurrence.phylumkey,
occurrence.class,
occurrence.classkey,
occurrence.\"order\",
occurrence.orderkey,
occurrence.family,
occurrence.familykey,
occurrence.genus,
occurrence.genuskey,
occurrence.species,
occurrence.specieskey,
occurrence.\"year\",
GBIF_EEARGCODE(1000, decimallatitude, decimallongitude, COALESCE(coordinateuncertaintyinmeters, 1000))"

# nolint end

birdcube_data_total <- download_occ_cube(
  sql_query = query_ang,
  file = "Angiosperm_data.csv",
  path = data_path,
  overwrite = TRUE
)

```

We get a big dataframe with all occurrences.

```{r}
# Explore dataframe
glimpse(birdcube_data_total)
```

# Select Flanders grid cells
The datacubes cover multiple zones although Flanders is present only in zone 31U. 


